# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FreeStreamDemo' do

end

target 'FreeStreamDemoTests' do

end

target 'FreeStreamDemoUITests' do

end
 pod 'FreeStreamer', '~> 3.5.4'
